MANIFEST = {'name': 'frontend',
 'label': 'backend',
 'summary': 'Sitio backend y constructor frontend.',
 'description': 'Sitio backend y constructor frontend.',
 'version': '1.0.0',
 'category': 'Operaciones',
 'author': 'SIPET',
 'sequence': '',
 'website': 'https://avancoop.org',
 'route': '/backend',
 'icon': 'fa-solid fa-globe',
 'depends': ['web'],
 'data': ['vistas/frontend.html'],
 'assets': {'css': [], 'js': [], 'description': ['static/description/web.svg'], 'img': []},
 'structure': {'router': ['controladores/frontend.py'],
               'models': ['modelos/frontend_db_models.py', 'modelos/frontend_store.py'],
               'views': ['vistas/frontend.html']},
 'installable': True,
 'application': True,
 'auto_install': False}

__all__ = ["MANIFEST"]
