[options]
domain = localhost
db_host = localhost
db_port = 5432
db_user = sipet
db_password = cambia_esto
dbfilter = ^%h$
show_db_path = False

admin_passwd = cambia_esta_clave
list_db = False

proxy_mode = True
workers = 4
max_cron_threads = 2
log_level = info
