from fastapi_modulo.modulos.web.repositorios.audit_repository import log_security_event as audit_log_security_event
from fastapi_modulo.modulos.web.repositorios.auth_repository import (
    consume_mfa_challenge as auth_consume_mfa_challenge,
    get_active_mfa_challenge as auth_get_active_mfa_challenge,
    log_login_attempt as auth_log_login_attempt,
    store_mfa_challenge as auth_store_mfa_challenge,
)
from fastapi_modulo.modulos.web.repositorios.preference_repository import upsert_user_preference as preference_upsert_user_preference
from fastapi_modulo.modulos.web.repositorios.security_repository import (
    count_active_sessions,
    consume_mfa_challenge,
    get_active_mfa_challenge,
    is_session_active,
    log_login_attempt,
    log_security_event,
    revoke_user_sessions,
    revoke_session,
    list_active_sessions,
    store_mfa_challenge,
    store_user_session,
    upsert_user_preference,
)
from fastapi_modulo.modulos.web.repositorios.session_repository import (
    count_active_sessions as session_count_active_sessions,
    is_session_active as session_is_session_active,
    list_active_sessions as session_list_active_sessions,
    revoke_session as session_revoke_session,
    revoke_user_sessions as session_revoke_user_sessions,
    store_user_session as session_store_user_session,
)
from fastapi_modulo.modulos.web.repositorios.security_maintenance_repository import (
    build_access_report,
    build_access_risk_report,
    build_backend_analytics_report,
    build_security_compliance_snapshot,
    build_security_alerts,
    cleanup_expired_mfa_challenges,
    cleanup_expired_sessions,
    detect_suspicious_login_patterns,
    export_backend_access_history_excel,
    export_security_audit_report_pdf,
    summarize_active_sessions,
    train_backend_access_risk_model,
)

__all__ = [
    "audit_log_security_event",
    "auth_consume_mfa_challenge",
    "auth_get_active_mfa_challenge",
    "auth_log_login_attempt",
    "auth_store_mfa_challenge",
    "build_access_report",
    "build_access_risk_report",
    "build_backend_analytics_report",
    "build_security_compliance_snapshot",
    "build_security_alerts",
    "cleanup_expired_mfa_challenges",
    "cleanup_expired_sessions",
    "count_active_sessions",
    "consume_mfa_challenge",
    "detect_suspicious_login_patterns",
    "export_backend_access_history_excel",
    "export_security_audit_report_pdf",
    "get_active_mfa_challenge",
    "is_session_active",
    "list_active_sessions",
    "log_login_attempt",
    "log_security_event",
    "preference_upsert_user_preference",
    "revoke_user_sessions",
    "revoke_session",
    "session_count_active_sessions",
    "session_is_session_active",
    "session_list_active_sessions",
    "session_revoke_session",
    "session_revoke_user_sessions",
    "session_store_user_session",
    "store_mfa_challenge",
    "store_user_session",
    "summarize_active_sessions",
    "train_backend_access_risk_model",
    "upsert_user_preference",
]
