MANIFEST = {'name': 'plantillas',
 'label': 'Plantillas',
 'summary': 'Core de plantillas.',
 'description': 'Core de plantillas.',
 'version': '1.0.0',
 'category': 'Operaciones',
 'author': 'SIPET',
 'sequence': '',
 'website': 'https://avancoop.org',
 'route': '/plantillas',
 'icon': 'fa-solid fa-layer-group',
 'fafa': 'fa-solid fa-layer-group',
 'depends': ['main'],
 'data': [],
 'assets': {'css': [], 'js': [], 'description': ['static/description/form.svg'], 'img': []},
 'structure': {'router': ['controladores/plantillas_forms.py'],
               'models': ['modelos/plantillas_db_models.py',
                          'modelos/plantillas_renderer.py',
                          'modelos/plantillas_schemas.py',
                          'modelos/plantillas_store.py',
                          'modelos/plantillas_submission_service.py',
                          'modelos/system_report_template.py']},
 'installable': True,
 'application': True,
 'auto_install': False}

__all__ = ["MANIFEST"]
