MANIFEST = {'name': 'ia',
 'label': 'IA',
 'summary': 'Router agregado de IA.',
 'description': 'Router agregado de IA.',
 'version': '1.0.0',
 'category': 'Operaciones',
 'author': 'SIPET',
 'sequence': '',
 'website': 'https://avancoop.org',
 'route': '/ia',
 'icon': '',
 'depends': ['web'],
 'data': ['vistas/ia.html', 'vistas/predictivo.html'],
 'assets': {'css': [], 'js': [], 'description': ['static/description/ia.svg'], 'img': []},
 'structure': {'router': ['controladores/ia_router.py',
                          'controladores/ia.py',
                          'controladores/router.py',
                          'controladores/predictivo.py'],
               'services': ['servicios/ia_service.py'],
               'providers': ['providers/base.py',
                             'providers/deepseek_provider.py',
                             'providers/ollama_provider.py',
                             'providers/openai_provider.py'],
               'views': ['vistas/ia.html', 'vistas/predictivo.html']},
 'installable': True,
 'application': True,
 'auto_install': False}

__all__ = ["MANIFEST"]
