from __future__ import annotations


BRUJULA_FIXED_INDICATORS = [
    {
        "nombre": "C2 - Indice de capitalizacion",
        "responsable": "Finanzas / Riesgos",
        "descripcion": "Mide la solidez patrimonial frente al activo total.",
        "objetivo": "Asegurar una base de capital suficiente.",
        "formula": "Capital contable / Activo total",
        "fuente_datos": "Balance general",
        "unidad": "%",
        "frecuencia": "Mensual",
        "linea_MAIN": "",
        "estandar_meta": ">=12.0%",
        "categoria": "Unidad institucional",
        "perspectiva": "Financiera",
        "semaforo_rojo": "<8.0%",
        "semaforo_verde": ">=15.0%",
        "orden": 1,
    },
    {
        "nombre": "C3 - Solvencia",
        "responsable": "Finanzas / Credito",
        "descripcion": "Relaciona la cartera neta con el activo total.",
        "objetivo": "Controlar la calidad del activo productivo.",
        "formula": "(Cartera total - Estimacion crediticia) / Activo total",
        "fuente_datos": "Balance general y cartera",
        "unidad": "%",
        "frecuencia": "Mensual",
        "linea_MAIN": "",
        "estandar_meta": ">=70.0%",
        "categoria": "Unidad institucional",
        "perspectiva": "Financiera",
        "semaforo_rojo": "<60.0%",
        "semaforo_verde": ">=75.0%",
        "orden": 2,
    },
    {
        "nombre": "C4 - Credito neto en riesgo",
        "responsable": "Credito / Riesgos",
        "descripcion": "Mide la proporcion de cartera vencida respecto de la cartera total.",
        "objetivo": "Monitorear el deterioro de cartera.",
        "formula": "Cartera vencida / Cartera total",
        "fuente_datos": "Reporte de cartera",
        "unidad": "%",
        "frecuencia": "Mensual",
        "linea_MAIN": "",
        "estandar_meta": "<=5.0%",
        "categoria": "Administracion",
        "perspectiva": "Financiera",
        "semaforo_rojo": ">8.0%",
        "semaforo_verde": "<=4.0%",
        "orden": 3,
    },
    {
        "nombre": "C5 - Cobertura de morosidad",
        "responsable": "Credito / Contabilidad",
        "descripcion": "Evalua el respaldo de estimaciones frente a cartera vencida.",
        "objetivo": "Proteger la cartera en riesgo.",
        "formula": "Estimacion crediticia / Cartera vencida",
        "fuente_datos": "Reporte de provisiones",
        "unidad": "%",
        "frecuencia": "Mensual",
        "linea_MAIN": "",
        "estandar_meta": ">=100.0%",
        "categoria": "Administracion",
        "perspectiva": "Financiera",
        "semaforo_rojo": "<80.0%",
        "semaforo_verde": ">=120.0%",
        "orden": 4,
    },
    {
        "nombre": "C6 - Cobertura de obligaciones a la vista",
        "responsable": "Tesoreria",
        "descripcion": "Mide la cobertura de liquidez inmediata sobre depositos a la vista.",
        "objetivo": "Mantener capacidad de respuesta en el corto plazo.",
        "formula": "(Disponibilidades + Inversiones) / Depositos a la vista",
        "fuente_datos": "Tesoreria y captaciones",
        "unidad": "%",
        "frecuencia": "Mensual",
        "linea_MAIN": "",
        "estandar_meta": ">=25.0%",
        "categoria": "Liquidez",
        "perspectiva": "Financiera",
        "semaforo_rojo": "<15.0%",
        "semaforo_verde": ">=35.0%",
        "orden": 5,
    },
    {
        "nombre": "C7 - Fondeo de activos improductivos",
        "responsable": "Finanzas",
        "descripcion": "Relaciona los activos improductivos con el capital contable.",
        "objetivo": "Limitar el peso de activos que no generan rendimiento.",
        "formula": "Activos improductivos / Capital contable",
        "fuente_datos": "Balance general",
        "unidad": "%",
        "frecuencia": "Mensual",
        "linea_MAIN": "",
        "estandar_meta": "<=25.0%",
        "categoria": "Utilizacion de recursos",
        "perspectiva": "Financiera",
        "semaforo_rojo": ">35.0%",
        "semaforo_verde": "<=20.0%",
        "orden": 6,
    },
    {
        "nombre": "C8 - Cobertura de gastos con ingresos",
        "responsable": "Finanzas",
        "descripcion": "Mide si los ingresos cubren el gasto total del periodo.",
        "objetivo": "Sostener la operacion con ingresos recurrentes.",
        "formula": "Ingresos / Gastos total",
        "fuente_datos": "Estado de resultados",
        "unidad": "%",
        "frecuencia": "Mensual",
        "linea_MAIN": "",
        "estandar_meta": ">=100.0%",
        "categoria": "Administracion",
        "perspectiva": "Financiera",
        "semaforo_rojo": "<90.0%",
        "semaforo_verde": ">=110.0%",
        "orden": 7,
    },
    {
        "nombre": "C9 - Autosuficiencia operativa",
        "responsable": "Finanzas",
        "descripcion": "Mide el peso del gasto administrativo sobre los ingresos.",
        "objetivo": "Controlar la eficiencia operativa.",
        "formula": "Gastos administrativos / Ingresos",
        "fuente_datos": "Estado de resultados",
        "unidad": "%",
        "frecuencia": "Mensual",
        "linea_MAIN": "",
        "estandar_meta": "<=60.0%",
        "categoria": "Administracion",
        "perspectiva": "Financiera",
        "semaforo_rojo": ">70.0%",
        "semaforo_verde": "<=50.0%",
        "orden": 8,
    },
    {
        "nombre": "C10 - ROA",
        "responsable": "Finanzas",
        "descripcion": "Mide la rentabilidad de los activos.",
        "objetivo": "Evaluar el rendimiento global del balance.",
        "formula": "Resultado neto / Activo total",
        "fuente_datos": "Estado de resultados y balance general",
        "unidad": "%",
        "frecuencia": "Mensual",
        "linea_MAIN": "",
        "estandar_meta": ">=1.0%",
        "categoria": "Rentabilidad",
        "perspectiva": "Financiera",
        "semaforo_rojo": "<0.0%",
        "semaforo_verde": ">=2.0%",
        "orden": 9,
    },
    {
        "nombre": "C11 - Margen financiero bruto",
        "responsable": "Finanzas",
        "descripcion": "Refleja el excedente entre ingresos y gastos financieros.",
        "objetivo": "Monitorear el margen financiero del periodo.",
        "formula": "Ingresos - Gastos financieros",
        "fuente_datos": "Estado de resultados",
        "unidad": "Moneda",
        "frecuencia": "Mensual",
        "linea_MAIN": "",
        "estandar_meta": ">=0",
        "categoria": "Rentabilidad",
        "perspectiva": "Financiera",
        "semaforo_rojo": "<0",
        "semaforo_verde": ">0",
        "orden": 10,
    },
    {
        "nombre": "O1 - Inversiones sobre activo total",
        "responsable": "Tesoreria",
        "descripcion": "Mide el peso de las inversiones dentro del activo total.",
        "objetivo": "Controlar la composicion de los activos liquidos.",
        "formula": "Inversiones / Activo total",
        "fuente_datos": "Balance general",
        "unidad": "%",
        "frecuencia": "Mensual",
        "linea_MAIN": "",
        "estandar_meta": "<=20.0%",
        "categoria": "Utilizacion de recursos",
        "perspectiva": "Financiera",
        "semaforo_rojo": ">30.0%",
        "semaforo_verde": "<=15.0%",
        "orden": 11,
    },
    {
        "nombre": "O2 - Financiamiento externo sobre activo total",
        "responsable": "Finanzas",
        "descripcion": "Mide la dependencia de financiamiento externo sobre el activo.",
        "objetivo": "Monitorear la exposicion a deuda externa.",
        "formula": "Prestamos externos / Activo total",
        "fuente_datos": "Balance general",
        "unidad": "%",
        "frecuencia": "Mensual",
        "linea_MAIN": "",
        "estandar_meta": "<=25.0%",
        "categoria": "Unidad institucional",
        "perspectiva": "Financiera",
        "semaforo_rojo": ">35.0%",
        "semaforo_verde": "<=20.0%",
        "orden": 12,
    },
    {
        "nombre": "O3 - Depositos de ahorro sobre activo total",
        "responsable": "Captaciones / Finanzas",
        "descripcion": "Mide la participacion del ahorro captado dentro del fondeo total.",
        "objetivo": "Fortalecer el fondeo estable.",
        "formula": "Depositos de ahorro / Activo total",
        "fuente_datos": "Balance general y captaciones",
        "unidad": "%",
        "frecuencia": "Mensual",
        "linea_MAIN": "",
        "estandar_meta": ">=50.0%",
        "categoria": "Unidad institucional",
        "perspectiva": "Financiera",
        "semaforo_rojo": "<40.0%",
        "semaforo_verde": ">=60.0%",
        "orden": 13,
    },
    {
        "nombre": "O4 - Capital social sobre activo total",
        "responsable": "Gobierno / Finanzas",
        "descripcion": "Mide el aporte del capital social dentro del activo total.",
        "objetivo": "Monitorear la fortaleza del patrimonio social.",
        "formula": "Capital social / Activo total",
        "fuente_datos": "Balance general",
        "unidad": "%",
        "frecuencia": "Mensual",
        "linea_MAIN": "",
        "estandar_meta": ">=8.0%",
        "categoria": "Unidad institucional",
        "perspectiva": "Financiera",
        "semaforo_rojo": "<5.0%",
        "semaforo_verde": ">=10.0%",
        "orden": 14,
    },
    {
        "nombre": "O5 - Reservas sobre activo total",
        "responsable": "Gobierno / Finanzas",
        "descripcion": "Mide la cobertura patrimonial de reservas frente al activo.",
        "objetivo": "Proteger el patrimonio institucional.",
        "formula": "Reservas / Activo total",
        "fuente_datos": "Balance general",
        "unidad": "%",
        "frecuencia": "Mensual",
        "linea_MAIN": "",
        "estandar_meta": ">=5.0%",
        "categoria": "Unidad institucional",
        "perspectiva": "Financiera",
        "semaforo_rojo": "<3.0%",
        "semaforo_verde": ">=8.0%",
        "orden": 15,
    },
    {
        "nombre": "O6 - Reservas sobre capital contable",
        "responsable": "Finanzas",
        "descripcion": "Mide la proporcion de reservas sobre el capital contable.",
        "objetivo": "Evaluar la robustez del fondo de reserva.",
        "formula": "Reservas / Capital contable",
        "fuente_datos": "Patrimonio",
        "unidad": "%",
        "frecuencia": "Mensual",
        "linea_MAIN": "",
        "estandar_meta": ">=30.0%",
        "categoria": "Junta directiva / gobernanza",
        "perspectiva": "Financiera",
        "semaforo_rojo": "<15.0%",
        "semaforo_verde": ">=40.0%",
        "orden": 16,
    },
    {
        "nombre": "O7 - Capital no comprometido",
        "responsable": "Finanzas",
        "descripcion": "Mide el nivel absoluto de capital contable disponible.",
        "objetivo": "Monitorear la base patrimonial.",
        "formula": "Capital contable",
        "fuente_datos": "Balance general",
        "unidad": "Moneda",
        "frecuencia": "Mensual",
        "linea_MAIN": "",
        "estandar_meta": "N/A",
        "categoria": "Unidad institucional",
        "perspectiva": "Financiera",
        "semaforo_rojo": "N/A",
        "semaforo_verde": "N/A",
        "orden": 17,
    },
    {
        "nombre": "O9 - Activos improductivos sobre activo total",
        "responsable": "Finanzas",
        "descripcion": "Mide el peso de activos improductivos dentro del activo total.",
        "objetivo": "Reducir recursos que no generan rendimiento.",
        "formula": "Activos improductivos / Activo total",
        "fuente_datos": "Balance general",
        "unidad": "%",
        "frecuencia": "Mensual",
        "linea_MAIN": "",
        "estandar_meta": "<=5.0%",
        "categoria": "Utilizacion de recursos",
        "perspectiva": "Financiera",
        "semaforo_rojo": ">10.0%",
        "semaforo_verde": "<=3.0%",
        "orden": 18,
    },
    {
        "nombre": "A1 - Rendimiento sobre cartera promedio",
        "responsable": "Finanzas / Credito",
        "descripcion": "Relaciona los ingresos con la cartera promedio del periodo.",
        "objetivo": "Evaluar el rendimiento del activo crediticio.",
        "formula": "Ingresos / Cartera total promedio",
        "fuente_datos": "Estado de resultados y cartera",
        "unidad": "%",
        "frecuencia": "Mensual",
        "linea_MAIN": "",
        "estandar_meta": ">=12.0%",
        "categoria": "Rentabilidad",
        "perspectiva": "Financiera",
        "semaforo_rojo": "<8.0%",
        "semaforo_verde": ">=15.0%",
        "orden": 19,
    },
    {
        "nombre": "A3 - Costo financiero sobre depositos promedio",
        "responsable": "Finanzas",
        "descripcion": "Mide el costo financiero asociado a los depositos promedio.",
        "objetivo": "Controlar el costo de fondeo captado.",
        "formula": "Gastos financieros / Depositos de ahorro promedio",
        "fuente_datos": "Estado de resultados y captaciones",
        "unidad": "%",
        "frecuencia": "Mensual",
        "linea_MAIN": "",
        "estandar_meta": "<=6.0%",
        "categoria": "Rentabilidad",
        "perspectiva": "Financiera",
        "semaforo_rojo": ">9.0%",
        "semaforo_verde": "<=4.0%",
        "orden": 20,
    },
    {
        "nombre": "A4 - Costo financiero por depositos",
        "responsable": "Finanzas",
        "descripcion": "Mide el costo del financiamiento externo.",
        "objetivo": "Controlar el costo de deuda.",
        "formula": "Gastos financieros / Prestamos externos",
        "fuente_datos": "Estado de resultados y deuda externa",
        "unidad": "%",
        "frecuencia": "Mensual",
        "linea_MAIN": "",
        "estandar_meta": "<=8.0%",
        "categoria": "Rentabilidad",
        "perspectiva": "Financiera",
        "semaforo_rojo": ">12.0%",
        "semaforo_verde": "<=6.0%",
        "orden": 21,
    },
    {
        "nombre": "A5 - Retorno sobre patrimonio",
        "responsable": "Finanzas",
        "descripcion": "Mide la rentabilidad neta del capital contable.",
        "objetivo": "Evaluar el retorno patrimonial.",
        "formula": "Resultado neto / Capital contable",
        "fuente_datos": "Estado de resultados y patrimonio",
        "unidad": "%",
        "frecuencia": "Mensual",
        "linea_MAIN": "",
        "estandar_meta": ">=10.0%",
        "categoria": "Rentabilidad",
        "perspectiva": "Financiera",
        "semaforo_rojo": "<5.0%",
        "semaforo_verde": ">=15.0%",
        "orden": 22,
    },
    {
        "nombre": "A6 - Cobertura liquida del ahorro",
        "responsable": "Tesoreria",
        "descripcion": "Mide la cobertura de liquidez inmediata sobre depositos de ahorro.",
        "objetivo": "Asegurar liquidez sobre ahorro captado.",
        "formula": "(Disponibilidades + Inversiones) / Depositos de ahorro",
        "fuente_datos": "Tesoreria y captaciones",
        "unidad": "%",
        "frecuencia": "Mensual",
        "linea_MAIN": "",
        "estandar_meta": ">=20.0%",
        "categoria": "Liquidez",
        "perspectiva": "Financiera",
        "semaforo_rojo": "<10.0%",
        "semaforo_verde": ">=30.0%",
        "orden": 23,
    },
    {
        "nombre": "A7 - Cobertura liquida de depositos a la vista",
        "responsable": "Tesoreria",
        "descripcion": "Mide la cobertura de liquidez inmediata sobre depositos a la vista.",
        "objetivo": "Gestionar liquidez de exigibilidad inmediata.",
        "formula": "(Disponibilidades + Inversiones) / Depositos a la vista",
        "fuente_datos": "Tesoreria y captaciones",
        "unidad": "%",
        "frecuencia": "Mensual",
        "linea_MAIN": "",
        "estandar_meta": ">=25.0%",
        "categoria": "Liquidez",
        "perspectiva": "Financiera",
        "semaforo_rojo": "<15.0%",
        "semaforo_verde": ">=35.0%",
        "orden": 24,
    },
    {
        "nombre": "A8 - Cobertura liquida de financiamiento externo",
        "responsable": "Tesoreria",
        "descripcion": "Mide la cobertura de liquidez inmediata sobre prestamos externos.",
        "objetivo": "Reducir la exposicion de corto plazo a financiamiento externo.",
        "formula": "(Disponibilidades + Inversiones) / Prestamos externos",
        "fuente_datos": "Tesoreria y deuda externa",
        "unidad": "%",
        "frecuencia": "Mensual",
        "linea_MAIN": "",
        "estandar_meta": ">=30.0%",
        "categoria": "Liquidez",
        "perspectiva": "Financiera",
        "semaforo_rojo": "<20.0%",
        "semaforo_verde": ">=40.0%",
        "orden": 25,
    },
    {
        "nombre": "Cr1 - Crecimiento de cartera vigente",
        "responsable": "Credito / Finanzas",
        "descripcion": "Mide la variacion de la cartera vigente respecto al periodo previo.",
        "objetivo": "Monitorear el crecimiento de la colocacion.",
        "formula": "(Cartera vigente actual - Cartera vigente previa) / Cartera vigente previa",
        "fuente_datos": "Cartera",
        "unidad": "%",
        "frecuencia": "Mensual",
        "linea_MAIN": "",
        "estandar_meta": ">=10.0%",
        "categoria": "Unidad institucional",
        "perspectiva": "Financiera",
        "semaforo_rojo": "<3.0%",
        "semaforo_verde": ">=15.0%",
        "orden": 26,
    },
    {
        "nombre": "Cr2 - Crecimiento de inversiones",
        "responsable": "Tesoreria",
        "descripcion": "Mide la variacion de inversiones respecto al periodo previo.",
        "objetivo": "Monitorear el crecimiento del portafolio liquido.",
        "formula": "(Inversiones actuales - Inversiones previas) / Inversiones previas",
        "fuente_datos": "Inversiones",
        "unidad": "%",
        "frecuencia": "Mensual",
        "linea_MAIN": "",
        "estandar_meta": ">=5.0%",
        "categoria": "Utilizacion de recursos",
        "perspectiva": "Financiera",
        "semaforo_rojo": "<0.0%",
        "semaforo_verde": ">=10.0%",
        "orden": 27,
    },
    {
        "nombre": "Cr3 - Crecimiento de depositos de ahorro",
        "responsable": "Captaciones / Finanzas",
        "descripcion": "Mide la variacion de depositos de ahorro respecto al periodo previo.",
        "objetivo": "Fortalecer el fondeo captado.",
        "formula": "(Depositos actuales - Depositos previos) / Depositos previos",
        "fuente_datos": "Captaciones",
        "unidad": "%",
        "frecuencia": "Mensual",
        "linea_MAIN": "",
        "estandar_meta": ">=8.0%",
        "categoria": "Unidad institucional",
        "perspectiva": "Financiera",
        "semaforo_rojo": "<2.0%",
        "semaforo_verde": ">=12.0%",
        "orden": 28,
    },
    {
        "nombre": "Cr4 - Crecimiento de financiamiento externo",
        "responsable": "Finanzas",
        "descripcion": "Mide la variacion de prestamos externos respecto al periodo previo.",
        "objetivo": "Controlar el crecimiento del endeudamiento.",
        "formula": "(Prestamos externos actuales - Prestamos externos previos) / Prestamos externos previos",
        "fuente_datos": "Deuda externa",
        "unidad": "%",
        "frecuencia": "Mensual",
        "linea_MAIN": "",
        "estandar_meta": "<=10.0%",
        "categoria": "Administracion",
        "perspectiva": "Financiera",
        "semaforo_rojo": ">20.0%",
        "semaforo_verde": "<=5.0%",
        "orden": 29,
    },
    {
        "nombre": "Cr5 - Crecimiento de capital social",
        "responsable": "Gobierno / Finanzas",
        "descripcion": "Mide la variacion del capital social respecto al periodo previo.",
        "objetivo": "Fortalecer el patrimonio social.",
        "formula": "(Capital social actual - Capital social previo) / Capital social previo",
        "fuente_datos": "Patrimonio",
        "unidad": "%",
        "frecuencia": "Mensual",
        "linea_MAIN": "",
        "estandar_meta": ">=5.0%",
        "categoria": "Unidad institucional",
        "perspectiva": "Financiera",
        "semaforo_rojo": "<1.0%",
        "semaforo_verde": ">=10.0%",
        "orden": 30,
    },
    {
        "nombre": "Cr6 - Crecimiento de reservas",
        "responsable": "Gobierno / Finanzas",
        "descripcion": "Mide la variacion de reservas respecto al periodo previo.",
        "objetivo": "Fortalecer la cobertura patrimonial.",
        "formula": "(Reservas actuales - Reservas previas) / Reservas previas",
        "fuente_datos": "Patrimonio",
        "unidad": "%",
        "frecuencia": "Mensual",
        "linea_MAIN": "",
        "estandar_meta": ">=5.0%",
        "categoria": "Junta directiva / gobernanza",
        "perspectiva": "Financiera",
        "semaforo_rojo": "<1.0%",
        "semaforo_verde": ">=10.0%",
        "orden": 31,
    },
    {
        "nombre": "Cr7 - Crecimiento de socios",
        "responsable": "Comercial / Servicio al Socio",
        "descripcion": "Mide la variacion del numero de socios respecto al periodo previo.",
        "objetivo": "Expandir la base social.",
        "formula": "(Socios actuales - Socios previos) / Socios previos",
        "fuente_datos": "Metricas de socios",
        "unidad": "%",
        "frecuencia": "Mensual",
        "linea_MAIN": "",
        "estandar_meta": ">=8.0%",
        "categoria": "Balance social",
        "perspectiva": "Social",
        "semaforo_rojo": "<3.0%",
        "semaforo_verde": ">=12.0%",
        "orden": 32,
    },
    {
        "nombre": "Cr8 - Crecimiento de activos totales",
        "responsable": "Finanzas",
        "descripcion": "Mide la variacion del activo total respecto al periodo previo.",
        "objetivo": "Monitorear la expansion institucional.",
        "formula": "(Activos actuales - Activos previos) / Activos previos",
        "fuente_datos": "Balance general",
        "unidad": "%",
        "frecuencia": "Mensual",
        "linea_MAIN": "",
        "estandar_meta": ">=8.0%",
        "categoria": "Unidad institucional",
        "perspectiva": "Financiera",
        "semaforo_rojo": "<3.0%",
        "semaforo_verde": ">=12.0%",
        "orden": 33,
    },
    {
        "nombre": "P2 - Ahorro promedio por socio",
        "responsable": "Captaciones / Servicio al Socio",
        "descripcion": "Mide el deposito de ahorro promedio por socio.",
        "objetivo": "Monitorear profundidad financiera por asociado.",
        "formula": "Depositos de ahorro / Socios",
        "fuente_datos": "Captaciones y metricas de socios",
        "unidad": "Moneda",
        "frecuencia": "Mensual",
        "linea_MAIN": "",
        "estandar_meta": "N/A",
        "categoria": "Balance social",
        "perspectiva": "Social",
        "semaforo_rojo": "N/A",
        "semaforo_verde": "N/A",
        "orden": 34,
    },
    {
        "nombre": "P5 - Socios por colaborador",
        "responsable": "Talento Humano / Servicio al Socio",
        "descripcion": "Mide cuántos socios atiende en promedio cada colaborador.",
        "objetivo": "Monitorear la capacidad operativa del equipo.",
        "formula": "Socios / Empleados",
        "fuente_datos": "Metricas de socios y empleados",
        "unidad": "Numero",
        "frecuencia": "Mensual",
        "linea_MAIN": "",
        "estandar_meta": "N/A",
        "categoria": "Administracion",
        "perspectiva": "Procesos",
        "semaforo_rojo": "N/A",
        "semaforo_verde": "N/A",
        "orden": 35,
    },
    {
        "nombre": "P12 - Resultado neto por colaborador",
        "responsable": "Talento Humano / Finanzas",
        "descripcion": "Mide el resultado neto generado por colaborador.",
        "objetivo": "Monitorear productividad economica del personal.",
        "formula": "Resultado neto / Empleados",
        "fuente_datos": "Estado de resultados y metricas de empleados",
        "unidad": "Moneda",
        "frecuencia": "Mensual",
        "linea_MAIN": "",
        "estandar_meta": "N/A",
        "categoria": "Administracion",
        "perspectiva": "Procesos",
        "semaforo_rojo": "N/A",
        "semaforo_verde": "N/A",
        "orden": 36,
    },
    {
        "nombre": "P16 - Gasto por colaborador",
        "responsable": "Talento Humano / Finanzas",
        "descripcion": "Mide el gasto total promedio por colaborador.",
        "objetivo": "Controlar el costo operativo del equipo.",
        "formula": "Gastos total / Empleados",
        "fuente_datos": "Estado de resultados y metricas de empleados",
        "unidad": "Moneda",
        "frecuencia": "Mensual",
        "linea_MAIN": "",
        "estandar_meta": "N/A",
        "categoria": "Administracion",
        "perspectiva": "Procesos",
        "semaforo_rojo": "N/A",
        "semaforo_verde": "N/A",
        "orden": 37,
    },
]


def get_brujula_fixed_indicators() -> list[dict]:
    items: list[dict] = []
    for index, item in enumerate(BRUJULA_FIXED_INDICATORS, start=1):
        current = dict(item)
        current["id"] = index
        current["orden"] = int(current.get("orden") or index)
        items.append(current)
    return items
