# Generated by Django 5.2.11 on 2026-02-17 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("socios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="socio",
            name="segmento",
            field=models.CharField(
                choices=[
                    ("hormiga", "Ahorrador Hormiga"),
                    ("gran_ahorrador", "Gran Ahorrador"),
                    ("inactivo", "Inactivo"),
                ],
                default="inactivo",
                max_length=30,
            ),
        ),
    ]
