MANIFEST = {'name': 'intelicoop',
 'label': 'Intelicoop',
 'summary': 'Analítica e inteligencia institucional.',
 'description': 'Analítica e inteligencia institucional.',
 'version': '1.0.0',
 'category': 'Operaciones',
 'author': 'SIPET',
 'sequence': '296',
 'website': 'https://avancoop.org',
 'route': '/inicio/intelicoop',
 'icon': 'fa fa-microchip',
 'depends': ['web'],
 'data': ['vistas/intelicoop.html'],
 'assets': {'css': [],
            'js': ['static/js/intelicoop.js'],
            'description': ['static/description/inteligencia.svg'],
            'img': []},
 'structure': {'router': ['controladores/intelicoop.py'],
               'models': ['modelos/intelicoop_db_models.py',
                          'modelos/intelicoop_models.py',
                          'modelos/intelicoop_scoring.py',
                          'modelos/intelicoop_store.py'],
               'views': ['vistas/intelicoop.html']},
 'installable': True,
 'application': True,
 'auto_install': False}

__all__ = ["MANIFEST"]
