from __future__ import annotations

from fastapi_modulo.modulos.intelicoop.modelos.store_analytics import (
    get_cohortes,
    get_dashboard_resumen,
    get_descriptive_analytics,
    get_pattern_discovery_summary,
    get_segmentation_propensity_summary,
    get_tendencias,
)
from fastapi_modulo.modulos.intelicoop.modelos.store_batch import (
    get_batch_overview,
    list_batch_alerts,
    list_batch_runs,
    run_batch_job,
    run_due_batch_jobs,
)
from fastapi_modulo.modulos.intelicoop.modelos.store_features import (
    get_foundation_overview,
    materialize_foundation_cut,
)
from fastapi_modulo.modulos.intelicoop.modelos.store_governance import (
    get_governance_overview,
    run_governance_refresh,
)
from fastapi_modulo.modulos.intelicoop.modelos.store_operativo import (
    create_campana,
    create_contacto_campania,
    create_credito,
    create_cuenta,
    create_historial_pago,
    create_prospecto,
    create_seguimiento_campania,
    create_socio,
    create_transaccion,
    ensure_intelicoop_schema,
    get_ahorros_resumen,
    get_basic_catalogs,
    get_credito,
    get_credito_detail,
    get_socio,
    list_campanas,
    list_contactos_campania,
    list_creditos,
    list_cuentas,
    list_historial_pagos,
    list_prospectos,
    list_seguimientos_campania,
    list_socios,
    list_transacciones,
)
from fastapi_modulo.modulos.intelicoop.modelos.store_scoring import (
    create_scoring_result,
    get_scoring_explainability,
    get_scoring_trace,
    list_scoring_results,
)

__all__ = [
    "ensure_intelicoop_schema",
    "list_socios",
    "get_socio",
    "create_socio",
    "list_creditos",
    "get_credito",
    "get_credito_detail",
    "create_credito",
    "list_historial_pagos",
    "create_historial_pago",
    "get_ahorros_resumen",
    "list_cuentas",
    "create_cuenta",
    "list_transacciones",
    "create_transaccion",
    "list_campanas",
    "create_campana",
    "list_prospectos",
    "create_prospecto",
    "list_contactos_campania",
    "create_contacto_campania",
    "list_seguimientos_campania",
    "create_seguimiento_campania",
    "create_scoring_result",
    "get_scoring_explainability",
    "get_scoring_trace",
    "list_scoring_results",
    "get_foundation_overview",
    "materialize_foundation_cut",
    "get_descriptive_analytics",
    "get_tendencias",
    "get_cohortes",
    "get_pattern_discovery_summary",
    "get_segmentation_propensity_summary",
    "get_dashboard_resumen",
    "get_basic_catalogs",
    "run_governance_refresh",
    "get_governance_overview",
    "get_batch_overview",
    "list_batch_runs",
    "list_batch_alerts",
    "run_batch_job",
    "run_due_batch_jobs",
]
