from __future__ import annotations

from fastapi_modulo.modulos.intelicoop.modelos.store_legacy import (
    create_campana,
    create_contacto_campania,
    create_credito,
    create_cuenta,
    create_historial_pago,
    create_prospecto,
    create_seguimiento_campania,
    create_socio,
    create_transaccion,
    ensure_intelicoop_schema,
    get_ahorros_resumen,
    get_basic_catalogs,
    get_credito,
    get_credito_detail,
    get_dashboard_resumen,
    get_socio,
    list_campanas,
    list_contactos_campania,
    list_creditos,
    list_cuentas,
    list_historial_pagos,
    list_prospectos,
    list_seguimientos_campania,
    list_socios,
    list_transacciones,
)

__all__ = [
    "ensure_intelicoop_schema",
    "list_socios",
    "get_socio",
    "create_socio",
    "list_creditos",
    "get_credito",
    "get_credito_detail",
    "create_credito",
    "list_historial_pagos",
    "create_historial_pago",
    "get_ahorros_resumen",
    "list_cuentas",
    "create_cuenta",
    "list_transacciones",
    "create_transaccion",
    "list_campanas",
    "create_campana",
    "list_prospectos",
    "create_prospecto",
    "list_contactos_campania",
    "create_contacto_campania",
    "list_seguimientos_campania",
    "create_seguimiento_campania",
    "get_basic_catalogs",
    "get_dashboard_resumen",
]
