MANIFEST = {'name': 'planificacion',
 'label': 'Estrategia y táctica',
 'summary': 'Planificación, POA, ciclo anual y tablero estratégico.',
 'description': 'Planificación, POA, ciclo anual y tablero estratégico.',
 'version': '1.0.0',
 'category': 'Operaciones',
 'author': 'SIPET',
 'sequence': '',
 'website': 'https://avancoop.org',
 'route': '/planes',
 'icon': 'fa-solid fa-chess-board',
 'depends': ['main'],
 'data': ['vistas/plan_estrategico.html',
          'vistas/poa.html',
          'vistas/poa_cal.html',
          'vistas/poa_gantt.html',
          'vistas/poa_tree.html'],
 'assets': {'css': ['static/css/plan_estrategico.css', 'static/css/poa.css'],
            'js': ['static/js/plan_estrategico.js', 'static/js/poa.js'],
            'description': ['static/description/plan.svg'],
            'img': []},
 'structure': {'router': ['controladores/annual_cycle_service.py',
                          'controladores/ejes_poa.py',
                          'controladores/kpis.py',
                          'controladores/notificaciones.py',
                          'controladores/plan_estrategico.py',
                          'controladores/poa.py'],
               'models': ['modelos/kpis_service.py',
                          'modelos/notificaciones_service.py',
                          'modelos/plan_estrategico_service.py',
                          'modelos/poa_service.py'],
               'views': ['vistas/plan_estrategico.html',
                         'vistas/poa.html',
                         'vistas/poa_cal.html',
                         'vistas/poa_gantt.html',
                         'vistas/poa_tree.html']},
 'installable': True,
 'application': True,
 'auto_install': False}

__all__ = ["MANIFEST"]
