from django.urls import path

from .views import (
    AlertasTempranasOperativasView,
    ColocacionPreaprobadosView,
    CampaniaListCreateView,
    MoraTempranaEvaluateView,
    MoraTempranaResumenView,
    ProspectoListView,
    ReglasAsociacionListView,
    ReglasAsociacionResumenView,
    ReportesSucursalProductoEjecutivoView,
    ReporteMensualRiesgoCrecimientoView,
    ResultadoMoraTempranaListView,
    ResultadoSegmentacionSocioListView,
    ScoringEvaluateView,
    ScoringSocioRecomendacionView,
    ScoringResumenView,
    DashboardEjecutivosOperativosView,
    DashboardSemaforosView,
    SegmentacionSociosPerfilesView,
    SegmentacionInteligenteRunView,
    SubmodulosIntegracionResumenView,
    ResultadoScoringBySocioView,
    ResultadoScoringBySolicitudView,
    ResultadoScoringListCreateView,
    ping,
)

urlpatterns = [
    path('campanas/', CampaniaListCreateView.as_view(), name='campania_list_create'),
    path('prospectos/', ProspectoListView.as_view(), name='prospecto_list'),
    path('ml/mora-temprana/', ResultadoMoraTempranaListView.as_view(), name='mora_temprana_list'),
    path('ml/alertas-tempranas/operativas/', AlertasTempranasOperativasView.as_view(), name='alertas_tempranas_operativas'),
    path('ml/reportes/mensual-riesgo-crecimiento/', ReporteMensualRiesgoCrecimientoView.as_view(), name='reporte_mensual_riesgo_crecimiento'),
    path('ml/reportes/consejo/exportables/', ReporteMensualRiesgoCrecimientoView.as_view(), name='reporte_consejo_exportables'),
    path('ml/mora-temprana/evaluar/', MoraTempranaEvaluateView.as_view(), name='mora_temprana_evaluar'),
    path('ml/mora-temprana/resumen/', MoraTempranaResumenView.as_view(), name='mora_temprana_resumen'),
    path('ml/segmentacion-socios/', ResultadoSegmentacionSocioListView.as_view(), name='segmentacion_socios_list'),
    path('ml/segmentacion-socios/perfiles/', SegmentacionSociosPerfilesView.as_view(), name='segmentacion_socios_perfiles'),
    path('ml/segmentacion-inteligente/ejecutar/', SegmentacionInteligenteRunView.as_view(), name='segmentacion_inteligente_run'),
    path('ml/reglas-asociacion/', ReglasAsociacionListView.as_view(), name='reglas_asociacion_list'),
    path('ml/reglas-asociacion/resumen/', ReglasAsociacionResumenView.as_view(), name='reglas_asociacion_resumen'),
    path('ml/submodulos/resumen/', SubmodulosIntegracionResumenView.as_view(), name='submodulos_integracion_resumen'),
    path('ml/dashboard/ejecutivos-operativos/', DashboardEjecutivosOperativosView.as_view(), name='dashboard_ejecutivos_operativos'),
    path('ml/dashboard/semaforos/', DashboardSemaforosView.as_view(), name='dashboard_semaforos'),
    path('ml/scoring/evaluar/', ScoringEvaluateView.as_view(), name='scoring_evaluar'),
    path('ml/scoring/socio/<int:socio_id>/recomendacion/', ScoringSocioRecomendacionView.as_view(), name='scoring_socio_recomendacion'),
    path('ml/colocacion/preaprobados/', ColocacionPreaprobadosView.as_view(), name='colocacion_preaprobados'),
    path('ml/reportes/sucursal-producto-ejecutivo/', ReportesSucursalProductoEjecutivoView.as_view(), name='reportes_sucursal_producto_ejecutivo'),
    path('ml/scoring/resumen/', ScoringResumenView.as_view(), name='scoring_resumen'),
    path('ml/scoring-resultados/', ResultadoScoringListCreateView.as_view(), name='scoring_resultados_list_create'),
    path('ml/scoring/<str:solicitud_id>/', ResultadoScoringBySolicitudView.as_view(), name='scoring_resultado_by_solicitud'),
    path('ml/scoring/socio/<int:socio_id>/', ResultadoScoringBySocioView.as_view(), name='scoring_resultado_by_socio'),
    path('ping/', ping),
]
