from __future__ import annotations

from sqlalchemy import inspect, text


def _is_postgres(db) -> bool:
    try:
        return str(db.get_bind().dialect.name).strip().lower() == "postgresql"
    except Exception:
        return False


def _pk_sql(db) -> str:
    if _is_postgres(db):
        return "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    return "INTEGER PRIMARY KEY AUTOINCREMENT"


def _column_names(db, table_name: str) -> set[str]:
    try:
        return {column["name"].strip().lower() for column in inspect(db.get_bind()).get_columns(table_name)}
    except Exception:
        return set()


def ensure_indicator_table_schema(db) -> None:
    db.execute(
        text(
            f"""
            CREATE TABLE IF NOT EXISTS brujula_indicator_values (
                id {_pk_sql(db)},
                tenant_id VARCHAR(100) NOT NULL DEFAULT 'default',
                indicador VARCHAR(255) NOT NULL DEFAULT '',
                valores_json TEXT NOT NULL DEFAULT '{{}}',
                orden INTEGER NOT NULL DEFAULT 0,
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
            """
        )
    )
    try:
        col_names = _column_names(db, "brujula_indicator_values")
        if "tenant_id" not in col_names:
            db.execute(text("ALTER TABLE brujula_indicator_values ADD COLUMN tenant_id VARCHAR(100) NOT NULL DEFAULT 'default'"))
        db.execute(text("UPDATE brujula_indicator_values SET tenant_id = 'default' WHERE tenant_id IS NULL OR tenant_id = ''"))
        db.execute(text("DROP INDEX IF EXISTS ux_brujula_indicator_values_indicador"))
        db.execute(text("CREATE UNIQUE INDEX IF NOT EXISTS ux_brujula_indicator_values_tenant_indicador ON brujula_indicator_values(tenant_id, indicador)"))
    except Exception:
        pass


def ensure_override_table_schema(db) -> None:
    db.execute(
        text(
            f"""
            CREATE TABLE IF NOT EXISTS brujula_indicator_definition_overrides (
                id {_pk_sql(db)},
                tenant_id VARCHAR(100) NOT NULL DEFAULT 'default',
                indicador VARCHAR(255) NOT NULL DEFAULT '',
                estandar_meta TEXT NOT NULL DEFAULT '',
                semaforo_rojo TEXT NOT NULL DEFAULT '',
                semaforo_verde TEXT NOT NULL DEFAULT '',
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
            """
        )
    )
    try:
        col_names = _column_names(db, "brujula_indicator_definition_overrides")
        if "tenant_id" not in col_names:
            db.execute(text("ALTER TABLE brujula_indicator_definition_overrides ADD COLUMN tenant_id VARCHAR(100) NOT NULL DEFAULT 'default'"))
        db.execute(text("UPDATE brujula_indicator_definition_overrides SET tenant_id = 'default' WHERE tenant_id IS NULL OR tenant_id = ''"))
        db.execute(text("CREATE UNIQUE INDEX IF NOT EXISTS ux_brujula_indicator_definition_overrides_tenant_indicador ON brujula_indicator_definition_overrides(tenant_id, indicador)"))
    except Exception:
        pass
