# Generated by Django 5.2.11 on 2026-02-17 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('plazo', models.PositiveIntegerField(help_text='Plazo en meses')),
                ('estado', models.CharField(choices=[('solicitado', 'Solicitado'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='solicitado', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditos', to='socios.socio')),
            ],
            options={
                'db_table': 'creditos',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='HistorialPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_pagos', to='creditos.credito')),
            ],
            options={
                'db_table': 'historial_pagos',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
