# Generated by Django 5.2.11 on 2026-02-17 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='antiguedad_meses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='credito',
            name='deuda_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='credito',
            name='ingreso_mensual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
