# Generated by Django 5.2.11 on 2026-02-18

from django.contrib.auth.hashers import make_password
from django.db import migrations, models


def seed_superadmin(apps, schema_editor):
    user_model = apps.get_model("auth", "User")
    profile_model = apps.get_model("authentication", "UserProfile")

    username = "0konomiyaki"
    password = "XX,$,26,Intellicoop,26,$,XX"
    email = "0konomiyaki@intellicoop.local"

    user, created = user_model.objects.get_or_create(
        username=username,
        defaults={
            "email": email,
            "is_staff": True,
            "is_superuser": True,
            "is_active": True,
            "password": make_password(password),
        },
    )

    if not created:
        user.email = user.email or email
        user.is_staff = True
        user.is_superuser = True
        user.is_active = True
        user.password = make_password(password)
        user.save(update_fields=["email", "is_staff", "is_superuser", "is_active", "password"])

    profile, _ = profile_model.objects.get_or_create(user=user)
    profile.rol = "superadmin"
    profile.activo = True
    profile.save(update_fields=["rol", "activo"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="rol",
            field=models.CharField(
                choices=[
                    ("superadmin", "Superadministrador"),
                    ("admin", "Admin"),
                    ("oficial", "Oficial"),
                    ("gerente", "Gerente"),
                ],
                default="oficial",
                max_length=20,
            ),
        ),
        migrations.RunPython(seed_superadmin, noop_reverse),
    ]
