# Generated by Django 5.2.11 on 2026-02-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_superadmin_seed"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="two_factor_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
