# Generated by Django 5.2.11 on 2026-02-18

from django.db import migrations, models


def migrate_old_roles(apps, schema_editor):
    profile_model = apps.get_model("authentication", "UserProfile")
    role_map = {
        "oficial": "auditor",
        "gerente": "jefe_departamento",
        "admin": "administrador",
    }

    for old_role, new_role in role_map.items():
        profile_model.objects.filter(rol=old_role).update(rol=new_role)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_userprofile_two_factor_enabled"),
    ]

    operations = [
        migrations.RunPython(migrate_old_roles, noop_reverse),
        migrations.AlterField(
            model_name="userprofile",
            name="rol",
            field=models.CharField(
                choices=[
                    ("superadmin", "Superadministrador"),
                    ("administrador", "Administrador"),
                    ("jefe_departamento", "Jefe de departamento"),
                    ("auditor", "Auditor"),
                ],
                default="auditor",
                max_length=20,
            ),
        ),
    ]
