# Generated by Django 5.2.11 on 2026-02-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_roles_to_new_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="celular",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="departamento",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="puesto_trabajo",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]
