# Generated by Django 5.2.11 on 2026-02-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_userprofile_extra_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="avatar_image",
            field=models.TextField(blank=True, default=""),
        ),
    ]
