# Generated by Django 5.2.11 on 2026-02-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_userprofile_avatar_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rol',
            field=models.CharField(choices=[('superadmin', 'Superadministrador'), ('admin_datos', 'Administrador de datos'), ('analista', 'Analista'), ('gerencia', 'Gerencia'), ('comercial_ejecutivo', 'Comercial / Ejecutivos'), ('riesgo_cobranza', 'Riesgo / Cobranza'), ('consejo', 'Consejo'), ('administrador', 'Administrador (legacy)'), ('jefe_departamento', 'Jefe de departamento (legacy)'), ('auditor', 'Auditor (legacy)')], default='analista', max_length=20),
        ),
    ]
