MANIFEST = {'name': 'multiempresa',
 'label': 'Multiempresa',
 'summary': 'Gestión y aislamiento por empresa.',
 'description': 'Gestión y aislamiento por empresa.',
 'version': '1.0.0',
 'category': 'Operaciones',
 'author': 'SIPET',
 'sequence': '1198',
 'website': 'https://avancoop.org',
 'route': '/multiempresa',
 'icon': 'fa-solid fa-building-user',
 'depends': ['main'],
 'data': ['vistas/multiempresa.html'],
 'assets': {'css': [],
            'js': ['static/js/multiempresa.js'],
            'description': ['static/description/multiempresa.svg'],
            'img': []},
 'structure': {'router': ['controladores/multiempresa.py'],
               'models': ['modelos/me_db_models.py', 'modelos/me_models.py', 'modelos/me_store.py'],
               'views': ['vistas/multiempresa.html']},
 'installable': True,
 'application': True,
 'auto_install': False}

__all__ = ["MANIFEST"]
