MANIFEST = {'name': 'multiempresa',
 'label': 'Multiempresa',
 'summary': 'Gestión y aislamiento por empresa.',
 'description': 'Gestión y aislamiento por empresa.',
 'version': '1.0.0',
 'category': 'Operaciones',
 'author': 'SIPET',
 'sequence': '500',
 'website': 'https://avancoop.org',
 'route': '/multiempresa',
 'icon': 'fa-solid fa-building-user',
 'fafa': 'fa-solid fa-building-user',
 'depends': ['web'],
 'data': ['vistas/multiempresa.html'],
 'assets': {'css': ['static/css/multiempresa.css'],
            'js': ['static/js/multiempresa.js'],
            'description': ['static/description/multiempresa.svg'],
            'img': []},
 'structure': {'router': ['controladores/multiempresa.py',
                           'controladores/multiempresa_page.py',
                           'controladores/multiempresa_api.py',
                           'controladores/multiempresa_access_service.py'],
               'models': ['modelos/me_db_models.py',
                          'modelos/me_models.py',
                          'modelos/me_store.py',
                          'modelos/me_repository.py',
                          'modelos/me_serializer.py',
                          'modelos/me_logo_service.py'],
               'views': ['vistas/multiempresa.html']},
 'installable': True,
 'application': True,
 'auto_install': False}

__all__ = ["MANIFEST"]
