[options]
domain = ejemplo.local
db_host = localhost
db_port = 5432
db_user = sipet
db_name = sipet_ejemplo
enabled = True

[superadmin]
superadmin_user = 0konomiyaki
superadmin_password = XX,$,26,sipet,26,$,XX
superadmin_email = alopez@avancoop.org

