[options]
domain = ejemplo.local
db_host = localhost
db_port = 5432
db_user = sipet
db_password = cambia_esto
db_name = sipet_ejemplo
admin_passwd = cambia_esta_clave
list_db = False
workers = 4
max_cron_threads = 2
proxy_mode = True
log_level = info

[superadmin]
; Único usuario con acceso a /base_datos/inicializar
superadmin_user = 0konomiyaki
superadmin_password = XX,$,26,sipet,26,$,XX
superadmin_email = alopez@avancoop.org
