MANIFEST = {'name': 'reportes',
 'label': 'Reportes',
 'summary': 'Modulo reportes del sistema SIPET.',
 'description': 'Modulo reportes del sistema SIPET.',
 'version': '1.0.0',
 'category': 'Operaciones',
 'author': 'SIPET',
 'sequence': '',
 'website': 'https://avancoop.org',
 'route': '/reportes',
 'icon': 'fa-regular fa-file-lines',
 'fafa': 'fa-regular fa-file-lines',
 'depends': [],
 'data': ['vistas/reportes.html'],
 'assets': {'css': [], 'js': [], 'description': [], 'img': []},
 'structure': {'router': ['controladores/reportes.py'],
               'services': ['servicios/advanced_reporting_system.py'],
               'views': ['vistas/reportes.html']},
 'installable': True,
 'application': True,
 'auto_install': False}

__all__ = ["MANIFEST"]
