MANIFEST = {'name': 'personalizacion',
 'label': 'Roles',
 'summary': 'Core de roles y permisos.',
 'description': 'Core de roles y permisos.',
 'version': '1.0.0',
 'category': 'Operaciones',
 'author': 'SIPET',
 'sequence': '',
 'website': 'https://avancoop.org',
 'route': '/personalizacion',
 'icon': '',
 'depends': ['main'],
 'data': ['vistas/personalizar.html', 'vistas/roles.html'],
 'assets': {'css': [], 'js': ['static/js/personalizar.js'], 'description': [], 'img': []},
 'structure': {'router': ['controladores/personalizar.py', 'controladores/roles.py'],
               'models': ['modelos/theme_system.py'],
               'views': ['vistas/personalizar.html', 'vistas/roles.html']},
 'installable': True,
 'application': True,
 'auto_install': False}

__all__ = ["MANIFEST"]
