MANIFEST = {'name': 'notificaciones',
 'label': 'Conversaciones',
 'summary': 'Notificaciones internas y mensajería.',
 'description': 'Notificaciones internas y mensajería.',
 'version': '1.0.0',
 'category': 'Operaciones',
 'author': 'SIPET',
 'sequence': '1',
 'website': 'https://avancoop.org',
 'route': '/notificaciones',
 'icon': 'fa-regular fa-envelope',
 'depends': ['main'],
 'data': ['vistas/conversaciones.html'],
 'assets': {'css': ['static/css/conversaciones.css'],
            'js': ['static/js/conversaciones.js'],
            'description': [],
            'img': []},
 'structure': {'router': ['controladores/conversaciones.py', 'controladores/notificaciones.py'],
               'models': ['modelos/global_notifications_service.py'],
               'views': ['vistas/conversaciones.html'],
               'docs': ['modulo.json']},
 'installable': True,
 'application': True,
 'auto_install': False}

__all__ = ["MANIFEST"]
