from django.urls import path

from .views import (
    AuditEventsRecentView,
    ProfileView,
    RegisterView,
    RoleAdminDatosView,
    RoleAdministradorView,
    RoleAnalistaView,
    RoleAuditorView,
    RoleComercialEjecutivoView,
    RoleConsejoView,
    RoleGerenciaView,
    RoleJefeDepartamentoView,
    RoleRiesgoCobranzaView,
    RoleSuperadministradorView,
    RoleCapabilitiesView,
    RolesCatalogView,
    TwoFactorPreferenceView,
    UserDetailManagementView,
    UsersManagementView,
)

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('users/', UsersManagementView.as_view(), name='users_management'),
    path('users/<int:user_id>/', UserDetailManagementView.as_view(), name='user_detail_management'),
    path('audit/events/', AuditEventsRecentView.as_view(), name='audit_events_recent'),
    path('2fa/', TwoFactorPreferenceView.as_view(), name='two_factor_preference'),
    path('permissions/me/', RoleCapabilitiesView.as_view(), name='role_capabilities_me'),
    path('roles/', RolesCatalogView.as_view(), name='roles_catalog'),
    path('roles/consejo/', RoleConsejoView.as_view(), name='role_consejo'),
    path('roles/comercial-ejecutivo/', RoleComercialEjecutivoView.as_view(), name='role_comercial_ejecutivo'),
    path('roles/analista/', RoleAnalistaView.as_view(), name='role_analista'),
    path('roles/admin-datos/', RoleAdminDatosView.as_view(), name='role_admin_datos'),
    path('roles/riesgo-cobranza/', RoleRiesgoCobranzaView.as_view(), name='role_riesgo_cobranza'),
    path('roles/gerencia/', RoleGerenciaView.as_view(), name='role_gerencia'),
    path('roles/auditor/', RoleAuditorView.as_view(), name='role_auditor'),
    path('roles/jefe-departamento/', RoleJefeDepartamentoView.as_view(), name='role_jefe_departamento'),
    path('roles/administrador/', RoleAdministradorView.as_view(), name='role_administrador'),
    path('roles/superadministrador/', RoleSuperadministradorView.as_view(), name='role_superadministrador'),
    path('roles/oficial/', RoleAuditorView.as_view(), name='role_oficial_legacy'),
    path('roles/gerente/', RoleJefeDepartamentoView.as_view(), name='role_gerente_legacy'),
    path('roles/admin/', RoleAdministradorView.as_view(), name='role_admin_legacy'),
]
