MANIFEST = {'name': 'pld',
 'label': 'PLD',
 'summary': 'Prevención de lavado de dinero.',
 'description': 'Prevención de lavado de dinero.',
 'version': '1.0.0',
 'category': 'Operaciones',
 'author': 'SIPET',
 'sequence': '',
 'website': 'https://avancoop.org',
 'route': '/pld',
 'icon': 'fa-solid fa-shield-halved',
 'fafa': 'fa-solid fa-shield-halved',
 'depends': ['main'],
 'data': ['vistas/pld.html'],
 'assets': {'css': [], 'js': [], 'description': ['static/description/pld.svg'], 'img': []},
 'structure': {'router': ['controladores/pld.py'], 'views': ['vistas/pld.html']},
 'installable': True,
 'application': True,
 'auto_install': False}

__all__ = ["MANIFEST"]
