MANIFEST = {'name': 'encuestas',
 'label': 'Encuestas',
 'summary': 'Campañas, constructor, respuesta y resultados.',
 'description': 'Campañas, constructor, respuesta y resultados.',
 'version': '1.0.0',
 'category': 'Operaciones',
 'author': 'SIPET',
 'sequence': '293',
 'website': 'https://avancoop.org',
 'route': '/encuestas',
 'icon': 'fa fa-square-poll-vertical',
 'depends': ['web'],
 'data': ['vistas/encuesta.html', 'vistas/encuesta_response.html'],
 'assets': {'css': ['static/css/encuesta.css'],
            'js': ['static/js/encuesta.js', 'static/js/encuesta_response.js'],
            'description': ['static/description/encuesta.svg'],
            'img': []},
 'structure': {'router': ['controladores/__init__.py', 'controladores/encuesta.py'],
               'models': ['modelos/__init__.py',
                          'modelos/encuestas_models.py',
                          'modelos/encuestas_question_catalog.py',
                          'modelos/encuestas_store.py',
                          'modelos/encuestas_tasks.py'],
               'views': ['vistas/encuesta.html', 'vistas/encuesta_response.html'],
               'docs': ['modulo.json', 'manifiesto.json']},
 'installable': True,
 'application': True,
 'auto_install': False}

__all__ = ["MANIFEST"]
