MANIFEST = {'name': 'empleados',
 'label': 'Organización',
 'fafa': 'fa-solid fa-sitemap',
 'summary': 'Usuarios, empleados, regiones y departamentos.',
 'description': 'Usuarios, empleados, regiones y departamentos.',
 'version': '1.0.0',
 'category': 'Operaciones',
 'author': 'SIPET',
 'sequence': '100',
 'website': 'https://avancoop.org',
 'route': '/inicio/departamentos',
 'icon': 'fa-solid fa-sitemap',
 'depends': ['web'],
 'data': ['vistas/departamentos.html',
          'vistas/empleados.html',
          'vistas/habilidades.html',
          'vistas/placeholder_no_access.html',
          'vistas/puestos_laborales.html',
          'vistas/regiones.html'],
 'assets': {'css': ['static/css/puestos_laborales.css'],
            'js': ['static/js/departamentos.js',
                   'static/js/puestos_laborales.js',
                   'static/js/org_chart_loader.js'],
            'description': ['static/description/empleados.svg'],
            'img': []},
 'pwa': {'features': [{'key': 'departamentos',
                       'label': 'Departamentos',
                       'description': 'Consulta y administración móvil de áreas organizacionales.',
                       'route': '/inicio/departamentos',
                       'offline_capable': False},
                      {'key': 'empleados',
                       'label': 'Colaboradores',
                       'description': 'Acceso rápido al catálogo de colaboradores.',
                       'route': '/empleados',
                       'offline_capable': False}],
         'shortcuts': [{'name': 'Departamentos',
                        'short_name': 'Areas',
                        'url': '/inicio/departamentos'},
                       {'name': 'Colaboradores',
                        'short_name': 'Empleados',
                        'url': '/empleados'}],
         'precache_urls': ['/inicio/departamentos']},
 'structure': {'router': ['controladores/departamentos.py',
                          'controladores/empleados.py',
                          'controladores/regiones.py'],
               'models': ['modelos/departamentos_service.py', 'modelos/puestos_laborales_store.py'],
               'views': ['vistas/departamentos.html',
                         'vistas/empleados.html',
                         'vistas/habilidades.html',
                         'vistas/placeholder_no_access.html',
                         'vistas/puestos_laborales.html',
                         'vistas/regiones.html']},
 'installable': True,
 'application': True,
 'auto_install': False}

__all__ = ["MANIFEST"]
