MANIFEST = {
    "name": "web",
    "label": "Configuración",
    "summary": "Servicios web compartidos para modulos SIPET.",
    "description": (
        "Modulo tecnico para centralizar logica compartida "
        "de acceso, render backend y entrega de assets entre modulos SIPET."
    ),
    "version": "1.0.0",
    "category": "Base",
    "author": "SIPET",
    "sequence": "700",
    "icon": "fa-solid fa-gear",
    "fafa": "fa-solid fa-gear",
    "website": "https://avancoop.org",
    "route": "/web",
    "depends": [],
    "data": [
        "README.md",
        "vistas/backend_nav_catalog.html",
        "vistas/backend_shell_script.html",
        "vistas/navbar.html",
        "vistas/sidebar.html",
        "vistas/sidebar_icons.html",
        "vistas/partials/floating_actions.html",
        "vistas/partials/navbar.html",
        "vistas/partials/page_shell.html",
        "vistas/partials/sidebar.html",
    ],
    "assets": {
        "css": ["static/css/backend_shell.css"],
        "js": [],
        "description": [],
        "img": [],
    },
    "structure": {
        "router": [
            "controladores/__init__.py",
            "controladores/auth_api.py",
            "controladores/auth_pages.py",
        "controladores/auth_passkey.py",
        "controladores/backend_auth.py",
        "controladores/backend_middleware.py",
        "controladores/backend_shell.py",
        "controladores/user_admin.py",
    ],
        "models": [
            "modelos/db_models.py",
            "modelos/enums.py",
            "modelos/schemas.py",
        ],
        "repositories": [
            "repositorios/auth_repository.py",
            "repositorios/preference_repository.py",
            "repositorios/security_repository.py",
            "repositorios/security_maintenance_repository.py",
            "repositorios/session_repository.py",
        ],
        "views": [
            "vistas/backend_nav_catalog.html",
            "vistas/backend_shell_script.html",
            "vistas/navbar.html",
            "vistas/sidebar.html",
            "vistas/sidebar_icons.html",
            "vistas/partials/floating_actions.html",
            "vistas/partials/navbar.html",
            "vistas/partials/page_shell.html",
            "vistas/partials/sidebar.html",
        ],
        "services": [
            "servicios/access_service.py",
            "servicios/analytics_service.py",
            "servicios/audit_report_service.py",
            "servicios/audit_service.py",
            "servicios/auth_response_service.py",
            "servicios/auth_service.py",
            "servicios/mfa_service.py",
            "servicios/module_tools.py",
            "servicios/passkey_service.py",
            "servicios/redis_security_service.py",
            "servicios/security_policy_service.py",
            "servicios/session_service.py",
            "servicios/template_context_service.py",
            "servicios/template_service.py",
            "servicios/tenant_observability_service.py",
        ],
        "tasks": [
            "tareas/audit_tasks.py",
            "tareas/cleanup_tasks.py",
            "tareas/security_tasks.py",
        ],
        "tests": [
            "tests/test_backend_middleware.py",
            "tests/test_module_tools.py",
            "tests/test_session_security_service.py",
            "tests/test_template_context_service.py",
            "tests/test_web_persistence.py",
        ],
    },
    "installable": True,
    "application": False,
    "auto_install": False,
}

__all__ = ["MANIFEST"]
