MANIFEST = {'name': 'proyectando',
 'label': 'Datos financieros',
 'summary': 'Proyecciones y herramientas financieras.',
 'description': 'Proyecciones y herramientas financieras.',
 'version': '1.0.0',
 'category': 'Operaciones',
 'author': 'SIPET',
 'sequence': '',
 'website': 'https://avancoop.org',
 'route': '/proyectando',
 'icon': 'fa-solid fa-chart-column',
 'depends': ['main'],
 'data': ['vistas/activo_fijo.html',
          'vistas/cartera_prestamos.html',
          'vistas/crecimiento_general.html',
          'vistas/datos_preliminares.html',
          'vistas/gastos.html',
          'vistas/otras_cuentas_activo.html',
          'vistas/presupuesto.html',
          'vistas/recursos_liquidos.html',
          'vistas/tablero.html',
          'vistas/tasa_referencia.html'],
 'assets': {'css': ['static/css/proyectando.css'],
            'js': ['static/js/activo_fijo.js',
                   'static/js/crecimiento_general.js',
                   'static/js/datos_preliminares.js',
                   'static/js/presupuesto.js'],
            'description': ['static/description/proyectando.svg'],
            'img': []},
 'structure': {'router': ['controladores/crecimiento_general.py',
                          'controladores/datos_preliminares.py',
                          'controladores/no_acceso.py',
                          'controladores/presupuesto.py',
                          'controladores/sucursales.py',
                          'controladores/tablero.py'],
               'models': ['modelos/crecimiento_general_store.py',
                          'modelos/data_store.py',
                          'modelos/datos_preliminares_store.py',
                          'modelos/presupuesto_service.py',
                          'modelos/proyectando_dashboard_service.py',
                          'modelos/proyectando_store_common.py'],
               'views': ['vistas/activo_fijo.html',
                         'vistas/cartera_prestamos.html',
                         'vistas/crecimiento_general.html',
                         'vistas/datos_preliminares.html',
                         'vistas/gastos.html',
                         'vistas/otras_cuentas_activo.html',
                         'vistas/presupuesto.html',
                         'vistas/recursos_liquidos.html',
                         'vistas/tablero.html',
                         'vistas/tasa_referencia.html']},
 'installable': True,
 'application': True,
 'auto_install': False}

__all__ = ["MANIFEST"]
