{
    'name': 'Avan Tickets',
    'summary': 'Gestión de tickets de soporte y dashboard unificado',
    'description': 'Módulo fusionado de odoo_website_helpdesk y odoo_website_helpdesk_dashboard. Incluye gestión de tickets, portal, dashboard y todos los assets.',
    'author': 'Tu Empresa',
    'website': 'https://www.tuempresa.com',
    'category': 'Helpdesk',
    'version': '1.0.0',
    'depends': [
        'base',
        'website',
        'mail',
        'project',
        'portal',
        'hr',
        'contacts',
        'web',
    ],
    'data': [
        'security/ir.model.access.csv',
        'security/odoo_website_helpdesk_security.xml',
        'security/odoo_website_helpdesk_groups.xml',
        'data/helpdesk_category_data.xml',
        'data/helpdesk_replay_template_data.xml',
        'data/helpdesk_type_data.xml',
        'data/ir_cron_data.xml',
        'data/ir_sequence_data.xml',
        'data/mail_template_data.xml',
        'data/ticket_stage_data.xml',
        'views/helpdesk_category_views.xml',
        'views/helpdesk_menu_views.xml',
        'views/helpdesk_tag_views.xml',
        'views/helpdesk_type_views.xml',
        'views/merge_ticket_views.xml',
        'views/ticket_stage_views.xml',
        'views/ticket_helpdesk_views.xml',
        'views/website_form.xml',
        'views/odoo_website_helpdesk_portal_templates.xml',
        'views/portal_templates.xml',
        'views/rating_form.xml',
        'views/team_helpdesk_views.xml',
        'views/res_config_settings_views.xml',
        'views/helpdesk_dashboard.xml',
        'views/dashboard_templates.xml',
        'views/helpdesk_ticket_report_template.xml',
        'views/menu_item.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'avan_tickets/static/src/js/*.js',
            'avan_tickets/static/src/js/lib/*.js',
            'avan_tickets/static/src/scss/*.css',
            'avan_tickets/static/src/css/*.css',
            'avan_tickets/static/description/assets/icons/*',
            'avan_tickets/static/description/assets/modules/*',
            'avan_tickets/static/description/assets/screenshots/*',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
}
