# Generated by Django 5.2.11 on 2026-02-18 03:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitica', '0001_initial'),
        ('creditos', '0002_credito_antiguedad_meses_credito_deuda_actual_and_more'),
        ('socios', '0002_socio_segmento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoScoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitud_id', models.CharField(db_index=True, max_length=120)),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ingreso_mensual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deuda_actual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('antiguedad_meses', models.PositiveIntegerField(default=0)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('recomendacion', models.CharField(max_length=30)),
                ('riesgo', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], max_length=10)),
                ('model_version', models.CharField(default='weighted_score_v1', max_length=60)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('credito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_scoring', to='creditos.credito')),
                ('socio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_scoring', to='socios.socio')),
            ],
            options={
                'db_table': 'resultados_scoring',
                'ordering': ['-id'],
            },
        ),
    ]
