# Generated by Django 5.2.11 on 2026-02-18 12:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analitica", "0002_resultadoscoring"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResultadoMoraTemprana",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("request_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("fecha_corte", models.DateField(default=django.utils.timezone.localdate)),
                ("cuota_estimada", models.DecimalField(decimal_places=2, max_digits=12)),
                ("pagos_90d", models.DecimalField(decimal_places=2, max_digits=12)),
                ("ratio_pago_90d", models.DecimalField(decimal_places=4, max_digits=6)),
                ("deuda_ingreso_ratio", models.DecimalField(decimal_places=4, max_digits=6)),
                ("prob_mora_30d", models.DecimalField(decimal_places=4, max_digits=6)),
                ("prob_mora_60d", models.DecimalField(decimal_places=4, max_digits=6)),
                ("prob_mora_90d", models.DecimalField(decimal_places=4, max_digits=6)),
                ("alerta", models.CharField(choices=[("baja", "Baja"), ("media", "Media"), ("alta", "Alta")], max_length=10)),
                ("model_version", models.CharField(default="mora_temprana_v1", max_length=60)),
                ("fuente", models.CharField(choices=[("batch", "Batch"), ("online", "Online")], default="batch", max_length=10)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "credito",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="resultados_mora_temprana", to="creditos.credito"),
                ),
                (
                    "socio",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="resultados_mora_temprana", to="socios.socio"),
                ),
            ],
            options={
                "db_table": "resultados_mora_temprana",
                "ordering": ["-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="resultadomoratemprana",
            constraint=models.UniqueConstraint(
                fields=("credito", "fecha_corte", "model_version", "fuente"),
                name="uniq_mora_temprana_credito_corte_version_fuente",
            ),
        ),
    ]
