# Generated by Django 5.2.11 on 2026-02-18 12:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analitica", "0003_resultadomoratemprana"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResultadoSegmentacionSocio",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("request_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("fecha_ejecucion", models.DateField(default=django.utils.timezone.localdate)),
                (
                    "segmento",
                    models.CharField(
                        choices=[("hormiga", "Ahorrador Hormiga"), ("gran_ahorrador", "Gran Ahorrador"), ("inactivo", "Inactivo")],
                        max_length=30,
                    ),
                ),
                ("saldo_total", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("total_movimientos", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("cantidad_movimientos", models.PositiveIntegerField(default=0)),
                ("dias_desde_ultimo_movimiento", models.PositiveIntegerField(blank=True, null=True)),
                ("total_creditos", models.PositiveIntegerField(default=0)),
                ("model_version", models.CharField(default="segmentacion_socios_v1", max_length=60)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "socio",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="resultados_segmentacion", to="socios.socio"),
                ),
            ],
            options={
                "db_table": "resultados_segmentacion_socios",
                "ordering": ["-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="resultadosegmentacionsocio",
            constraint=models.UniqueConstraint(
                fields=("socio", "fecha_ejecucion", "model_version"),
                name="uniq_segmentacion_socio_fecha_version",
            ),
        ),
    ]
