# Generated by Django 5.2.11 on 2026-02-18 13:12

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analitica", "0004_resultadosegmentacionsocio"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReglaAsociacionProducto",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("request_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("fecha_ejecucion", models.DateField(default=django.utils.timezone.localdate)),
                ("antecedente", models.CharField(db_index=True, max_length=120)),
                ("consecuente", models.CharField(db_index=True, max_length=120)),
                ("soporte", models.DecimalField(decimal_places=4, max_digits=6)),
                ("confianza", models.DecimalField(decimal_places=4, max_digits=6)),
                ("lift", models.DecimalField(decimal_places=4, max_digits=8)),
                ("casos_antecedente", models.PositiveIntegerField(default=0)),
                ("casos_regla", models.PositiveIntegerField(default=0)),
                ("oportunidad_comercial", models.CharField(max_length=255)),
                ("vigente", models.BooleanField(default=True)),
                ("model_version", models.CharField(default="asociacion_productos_v1", max_length=60)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "reglas_asociacion_productos",
                "ordering": ["-lift", "-confianza", "-soporte", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="reglaasociacionproducto",
            constraint=models.UniqueConstraint(
                fields=("fecha_ejecucion", "antecedente", "consecuente", "model_version"),
                name="uniq_regla_asociacion_fecha_ant_cons_version",
            ),
        ),
    ]
