# Generated by Django 5.2.11 on 2026-02-18 13:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analitica", "0005_reglaasociacionproducto"),
    ]

    operations = [
        migrations.CreateModel(
            name="EjecucionPipeline",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("request_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("pipeline", models.CharField(db_index=True, max_length=120)),
                ("fecha_inicio", models.DateTimeField()),
                ("fecha_fin", models.DateTimeField()),
                ("duracion_ms", models.PositiveIntegerField(default=0)),
                ("estado", models.CharField(choices=[("ok", "OK"), ("error", "Error")], default="ok", max_length=10)),
                ("detalle", models.CharField(blank=True, default="", max_length=255)),
                ("idempotency_key", models.CharField(db_index=True, max_length=180)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ejecuciones_pipeline",
                "ordering": ["-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="ejecucionpipeline",
            constraint=models.UniqueConstraint(
                fields=("pipeline", "idempotency_key"),
                name="uniq_pipeline_idempotency_key",
            ),
        ),
    ]
