# Generated by Django 5.2.11 on 2026-02-18 14:00

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analitica", "0006_ejecucionpipeline"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertaMonitoreo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("request_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("ambito", models.CharField(db_index=True, max_length=40)),
                ("metrica", models.CharField(db_index=True, max_length=80)),
                ("valor", models.DecimalField(decimal_places=4, max_digits=12)),
                ("umbral", models.CharField(max_length=60)),
                ("severidad", models.CharField(choices=[("info", "Info"), ("warn", "Warn"), ("critical", "Critical")], default="warn", max_length=10)),
                ("escalamiento", models.CharField(default="equipo_analitica", max_length=100)),
                ("estado", models.CharField(choices=[("activa", "Activa"), ("resuelta", "Resuelta")], default="activa", max_length=10)),
                ("detalle", models.CharField(blank=True, default="", max_length=255)),
                ("fecha_evento", models.DateTimeField(default=django.utils.timezone.now)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "alertas_monitoreo",
                "ordering": ["-id"],
            },
        ),
    ]
