# Generated by Django 5.2.11 on 2026-02-18 16:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitica', '0007_alertamonitoreo'),
        ('socios', '0002_socio_segmento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoCampania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ejecutivo_id', models.CharField(db_index=True, max_length=60)),
                ('canal', models.CharField(max_length=30)),
                ('estado_contacto', models.CharField(choices=[('pendiente', 'Pendiente'), ('contactado', 'Contactado'), ('no_localizado', 'No localizado')], default='pendiente', max_length=20)),
                ('fecha_contacto', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('campania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='analitica.campania')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos_campania', to='socios.socio')),
            ],
            options={
                'db_table': 'contactos_campania',
                'ordering': ['-id'],
                'constraints': [models.UniqueConstraint(fields=('campania', 'socio'), name='uniq_contacto_campania_socio')],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoConversionCampania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('lista', models.CharField(max_length=30)),
                ('etapa', models.CharField(max_length=30)),
                ('conversion', models.BooleanField(default=False)),
                ('monto_colocado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_evento', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('campania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='analitica.campania')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos_campania', to='socios.socio')),
            ],
            options={
                'db_table': 'seguimiento_conversion_campania',
                'ordering': ['-id'],
                'constraints': [models.UniqueConstraint(fields=('campania', 'socio', 'lista'), name='uniq_seguimiento_campania_socio_lista')],
            },
        ),
    ]
