# Generated by Django 5.2.11 on 2026-02-18 17:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analitica', '0008_contactocampania_seguimientoconversioncampania'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('modulo', models.CharField(db_index=True, max_length=60)),
                ('accion', models.CharField(db_index=True, max_length=120)),
                ('resultado', models.CharField(choices=[('ok', 'OK'), ('error', 'Error')], db_index=True, default='ok', max_length=10)),
                ('actor_username', models.CharField(blank=True, default='', max_length=150)),
                ('target_tipo', models.CharField(blank=True, default='', max_length=60)),
                ('target_id', models.CharField(blank=True, default='', max_length=120)),
                ('ip_origen', models.CharField(blank=True, default='', max_length=64)),
                ('detalle', models.JSONField(blank=True, default=dict)),
                ('fecha_evento', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'eventos_auditoria',
                'ordering': ['-id'],
            },
        ),
    ]
