MANIFEST = {'name': 'presupuesto',
 'label': 'Presupuesto',
 'summary': 'Modulo presupuesto del sistema SIPET.',
 'description': 'Modulo presupuesto del sistema SIPET.',
 'version': '1.0.0',
 'category': 'Operaciones',
 'author': 'SIPET',
 'sequence': '',
 'website': 'https://avancoop.org',
 'route': '/presupuesto',
 'icon': '',
 'depends': ['main'],
 'data': [],
 'assets': {'css': [], 'js': [], 'description': ['static/description/presupuesto.svg'], 'img': []},
 'structure': {'router': ['controladores/presupuesto.py'],
               'models': ['modelos/presupuesto_dashboard_service.py']},
 'installable': True,
 'application': True,
 'auto_install': False}

__all__ = ["MANIFEST"]
